### ISSUE TITLE
do() doesn't respect set.seed()?

### ISSUE THREAD

**Issue by beanumber** [rpruim/mosaic#431] opened 2015-03-13 02:38 UTC
```{r}
head(sample(1:100))
```

The first time I did this, I got:

64, 86, 31, 93, 52, 75, ...

But, I get a different thing everytime I knit this, as expected.

```{r}
set.seed(50)
head(sample(1:100))
```

Now I get the **same thing** every time I knit this, as expected. 

71, 44, 20, 75, 50, 5, ...

```{r, message=FALSE}
require(mosaic)
require(mosaicData)
bstrap <- do(1000) * cor(length ~ width, data=resample(KidsFeet))
favstats(bstrap)
```

When I knit this the first time, the mean was 0.6320324. **Why does it change every time I knit**!! Shouldn't it be the same?

```{r}
head(resample(KidsFeet))
```

Josh, Edward, Mark, ...
This seems to be working as expected.

```{r}
head(sample(1:100))
```

55, 16, 26, 17, 5, ...

Base R is still returning the same sequence of random numbers. 

So the problem seems to be with `do()`. Any idea what is going on here?

**Comment by rpruim** [comment] 2015-03-17 19:01
If the `parallel` package is installed, then it is used to speed things up.  Random number generation in a parallel environment is a bit different because one needs to think about how child processes generate random values with respect to parents and siblings.

So you have two options:

 * turn off `parallel` using `do(1000, parallel=FALSE) *`
 * tell the `parallel` package that you want reproducibility:

```
> RNGkind("L'Ecuyer-CMRG")
> set.seed(123); parallel::mc.reset.stream(); do(2) * head(resample(KidsFeet), 3)
       name birthmonth birthyear length width sex biggerfoot domhand orig.ids .row .index
35    Peter          4        88   24.7   8.6   B          R       L       35    1      1
9   Eleanor          5        88   23.6   9.3   G          R       R        9    2      1
22     Josh          7        88   24.4   8.6   B          L       R       22    3      1
37 Teshanna          3        88   26.0   9.0   G          L       R       37    1      2
16     Kate          4        88   23.7   7.9   G          R       R       16    2      2
36   Hannah          3        88   22.9   8.5   G          L       R       36    3      2
> set.seed(123); parallel::mc.reset.stream(); do(2) * head(resample(KidsFeet), 3)
       name birthmonth birthyear length width sex biggerfoot domhand orig.ids .row .index
35    Peter          4        88   24.7   8.6   B          R       L       35    1      1
9   Eleanor          5        88   23.6   9.3   G          R       R        9    2      1
22     Josh          7        88   24.4   8.6   B          L       R       22    3      1
37 Teshanna          3        88   26.0   9.0   G          L       R       37    1      2
16     Kate          4        88   23.7   7.9   G          R       R       16    2      2
36   Hannah          3        88   22.9   8.5   G          L       R       36    3      2
```
I suppose we could consider doing something to wrap up the call to `mc.reset.stream()`, but I don't think there is any way to get `set.seed()` by itself to do what you were expecting when using parallel random number generation.

See the help for `mcparallel` and `mclapply` for more info.

**Comment by rpruim** [comment] 2015-03-18 02:22
Regarding the possibility of changing the default to `parallel = FALSE`:

One of the early complaints about `do()` was that is was slow, so I rewrote it trying to squeeze out speed wherever I was able.  Having `do()` run 2 or 4 or more times faster (depending on the number of corse available to your R kernel) is a good thing and I think I like that as the default.  So there are other options I like better than changing this default:

	1) Do nothing, but let people know about the issue, including in the documentation for do()
	2) Have some global option that is used to determine the default behavior so that you can choose once and have it work for all uses of `do()` in the session
	3) Create something like `set.pseed()` that changes the RNG algorithm, sets the seed, and calls `mc.reset.stream()`.

**Comment by nicholasjhorton** [comment] 2015-04-24 13:48
Can we find a time to talk about this?

Nick

> On Mar 17, 2015, at 10:22 PM, Randall Pruim <notifications@github.com> wrote:
> 
> Regarding the possibility of changing the default to parallel = FALSE:
> 
> One of the early complaints about do() was that is was slow, so I rewrote it trying to squeeze out speed wherever I was able. Having do() run 2 or 4 or more times faster (depending on the number of corse available to your R kernel) is a good thing and I think I like that as the default. So there are other options I like better than changing this default:
> 
> 1) Do nothing, but let people know about the issue, including in the documentation for do()
> 2) Have some global option that is used to determine the default behavior so that you can choose once and have it work for all uses of `do()` in the session
> 3) Create something like `set.pseed()` that changes the RNG algorithm, sets the seed, and calls `mc.reset.stream()`.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment] 2015-04-27 00:46
Here is another option:  Only use parallel if it is *loaded*.  We have been using it if it was *installed*.

**Comment by rpruim** [comment] 2015-04-27 01:02
Currently implementing (a) use of parallel only if loaded (i.e., in the search path), (b) `set.pseed()` to simplifying setting seeds with `parallel` loaded, and (c) a message reminding users to use `set.pseed()` if  the `parallel` package is loaded and the `parallel` argument is set to `TRUE` (the default) in `do()`:

```
> set.seed(123); do(2) * resample(1:10, 2)
Using `parallel'.  Set seed with set.pseed().
  V1 V2
1  5  1
2  9  7
> set.seed(123); do(2) * resample(1:10, 2)
Using `parallel'.  Set seed with set.pseed().
  V1 V2
1 10  8
2  3  2
> set.pseed(123); do(2) * resample(1:10, 2)
Using `parallel'.  Set seed with set.pseed().
  V1 V2
1  9  2
2  7  8
> set.pseed(123); do(2) * resample(1:10, 2)
Using `parallel'.  Set seed with set.pseed().
  V1 V2
1  9  2
2  7  8
> set.seed(123); do(2, parallel=FALSE) * resample(1:10, 2)
  V1 V2
1  8  7
2 10  6
> set.seed(123); do(2, parallel=FALSE) * resample(1:10, 2)
  V1 V2
1  8  7
2 10  6
```

**Comment by rpruim** [comment] 2015-04-27 02:09
I'm renaming `set.pseed()` to `set_pseed()`.

**Comment by rpruim** [comment] 2015-04-29 05:54
Any complaints with this "solution"?  If not, I'll close this.

**Comment by nicholasjhorton** [comment] 2015-04-29 11:06
This sounds reasonable to me.  Is it worthwhile adding a note in the documentation?

Nick

> On Apr 29, 2015, at 1:54 AM, Randall Pruim <notifications@github.com> wrote:
> 
> Any complaints with this "solution"? If not, I'll close this.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by rpruim** [comment] 2015-05-05 02:32
I think we are alls systems go here except for deciding on a name for `set_pseed()`.  I've added examples to both `?set_pseed` and `?do` and I've also added a "see also" pointing from `?do` to `?set_pseed`.  

But I'm not sure I like the name.  We don't use underscore elsewhere, and I'm not sure I like the letter p either.  Some other possibilities:

```r
set.seed2() # second version of set.seed() 
set.rseed()  # r for random 
```
Any other suggestions?

**Comment by dtkaplan** [comment] 2015-05-05 02:38
It’s something that someone would have to look to help() anyways, so just
make it explicit

set_seed_for_parallel_do()

-Danny
​

**Comment by rpruim** [comment] 2015-05-05 02:41
I don't want it to be so long, and it works even if you are not using the parallel package.

I have added a message to the the output of `do()` when the `parallel` package is on the search path:
```
> require(parallel)
Loading required package: parallel
> do(3) * resample(1:10)
Using `parallel'.  Set seed with set.rseed().
  V1 V2 V3 V4 V5 V6 V7 V8 V9 V10
1  3  2  9  3  7  2  6  7  1   1
2  8 10  7  3  2  5  7  6  2  10
3  4  6  4  7  1  4  8  4  2   5
```

**Closed** 2015-05-07 11:46 UTC
